### ISSUE TITLE
Camera, Gallery

### ISSUE THREAD

**Issue by PranavPrakasan07** [isa-vit/CodeY#10]
Implement accessing images from the gallery, and taking images via camera pressing buttons in the respective screen

**Comment by unnikrishnan2002** [comment]
Hey sorry I can't work on this issue because I am not familiar to kotlin and I didn't set it up on my local machine before asking for assignment @PranavPrakasan07. I thought it would be java

**Comment by PranavPrakasan07** [comment]
@unnikrishnan2002 You are free to use Java/Kotlin. 

If you can make necessary changes to the files associated, you can work on the same, otherwise, try a different issue.
