### ISSUE TITLE
Night mode switch

### ISSUE THREAD

**Issue by PranavPrakasan07** [isa-vit/CodeY#2]
Implement the light-mode night-mode switch

**Comment by garvsgit** [comment]
The switch should be in which activity?

**Comment by garvsgit** [comment]
Can you also assign me this issue? The UI needs a lot of work before this works properly. But I can set up the code for the switching.

**Comment by PranavPrakasan07** [comment]
> @PranavPrakasan07 The switch should be in which activity?

You can keep it in the home, as well as editor screens.

**Comment by PranavPrakasan07** [comment]
@garvsgit You've been assigned, you can start working.
